export const blogPosts = [
  {
    id: 1,
    title: "Top 10 Modern Construction Techniques in 2025",
    excerpt: "A look at the latest construction methods shaping the future of buildings.",
    slug: "modern-construction-techniques-2025",
    date: "Aug 15, 2025",
    image: "/top-10-modern-construction.jfif",
  },
  {
    id: 2,
    title: "Green Buildings: How Sustainable Construction is Changing Cities",
    excerpt: "Learn how eco-friendly materials and designs are making construction sustainable.",
    slug: "green-buildings-sustainable-construction",
    date: "Aug 15, 2025",
    image: "/green-buildings-how.jfif",
  },
  {
    id: 3,
    title: "AI and Robotics in Construction Industry",
    excerpt: "Discover how artificial intelligence and robots are speeding up construction projects.",
    slug: "ai-robotics-in-construction",
    date: "Aug 15, 2025",
    image: "/ai-robotics-in-construction (2).jfif",
  },
  {
    id: 4,
    title: "Smart Homes: Future of Residential Construction",
    excerpt: "Explore how smart technology is becoming part of modern home construction.",
    slug: "smart-homes-future-construction",
    date: "Aug 15, 2025",
    image: "/smart-home-future-ofresidential-counstruction.jfif",
  },
  {
    id: 5,
    title: "Best Construction Materials for Durability in 2025",
    excerpt: "A guide to the strongest and most reliable materials used in construction today.",
    slug: "best-construction-materials-2025",
    date: "Aug 15, 2025",
    image: "/best-construction-materials-2025.jfif",
  },
  {
    id: 6,
    title: "How 3D Printing is Revolutionizing Construction",
    excerpt: "From houses to bridges, see how 3D printing is transforming construction projects.",
    slug: "3d-printing-in-construction",
    date: "Aug 15, 2025",
    image: "/3d-printing-in-construction.lnk",
  },
  {
    id: 7,
    title: "Safety in Construction: Best Practices for 2025",
    excerpt: "Essential safety measures every construction project should follow.",
    slug: "safety-in-construction-2025",
    date: "Aug 15, 2025",
    image: "/",
  },
  {
    id: 8,
    title: "Future of Skyscrapers: Tall, Smart, and Sustainable",
    excerpt: "Learn how new skyscraper designs are changing city skylines.",
    slug: "future-of-skyscrapers",
    date: "Aug 15, 2025",
    image: "/",
  },
]
